name: PracticeBot
version: '1.6'
main: com.pallux.practicebot.PracticeBot
api-version: '1.17'
author: Pallux
description: AI PvP Bots for Practice (Made for Practice Setup from Pallux)
depend: [Citizens]

commands:
  pbarea:
    description: Manages PracticeBot areas.
    usage: /<command>
    aliases: [pb, practicebot]
    permission: practicebot.admin

permissions:
  practicebot.admin:
    description: Gives access to all PracticeBot commands.
    default: op