# =================================================================== #
#                       PracticeBot Configuration                     #
# =================================================================== #

# General plugin settings
settings:
  prefix: "<gradient:#FF6B6B:#4ECDC4>PracticeBot</gradient> <gray>»</gray> "

# --- Bot AI and Behavior ---
bot-behavior:
  # Time in seconds before a killed bot respawns in its area.
  respawn-delay: 5
  # Maximum distance (in blocks) a bot can see and target an enemy.
  detection-range: 32.0
  # The distance (in blocks) at which a bot will stop chasing and start fighting.
  attack-range: 3.5

# --- Combat Settings ---
combat:
  # Delay between bot attacks (in ticks, 20 ticks = 1 second). Lower is faster.
  attack-delay: 12
  # Chance for the bot to strafe sideways during melee (0.0 to 1.0).
  strafe-chance: 0.7
  # The maximum number of bots that can target a single human player at the same time.
  max-player-attackers: 2

  # Fishing Rod Settings
  # Cooldown in ticks between fishing rod uses (60 = 3 seconds)
  rod-cooldown: 60

  # Potion Settings
  # Chance for bot to throw a potion when in range (0.0 to 1.0)
  potion-chance: 0.3
  # Cooldown in ticks between potion throws (100 = 5 seconds)
  potion-cooldown: 100

  # Trident Settings
  # Cooldown in ticks between trident throws (80 = 4 seconds)
  trident-cooldown: 80

  # Bot vs. Bot Combat Settings
  bot-vs-bot:
    # If true, bots will fight each other if no players are available to target.
    enabled: true
    # The maximum number of bots that can target a single bot at the same time.
    max-bot-attackers: 1

# --- Movement Settings for the Custom AI ---
movement:
  # Speed multiplier while chasing a distant target (1.0 = normal player sprint speed).
  chase-speed: 1.4
  # Speed multiplier during close-quarters melee combat.
  melee-speed: 1.2

# --- Performance Settings ---
performance:
  # How often to update the bot's AI (in ticks). 1 is the most responsive.
  ai-tick-rate: 1
  # The delay in ticks between spawning each bot in a large batch.
  # A small delay prevents server lag when spawning many bots at once.
  spawn-delay-ticks: 2

# --- Visual/Other Settings ---
area-settings:
  selection-tool: STONE_AXE

# Bot name without numbers - just "Practice Bot"
bot-name-format: "Practice Bot"

hologram:
  enabled: true
  format: "<gold>{name}</gold>\n<red>❤ {health}/{max_health}</red>"

# This section is managed automatically by the /pbarea command. Do not edit manually.
areas: {}